#!/bin/sh
#
# Restore ALSA mixer state (WM8960 headphone volume defaults to 0 after boot).
#

start() {
	printf "Restoring ALSA mixer state: "
	alsactl restore
	echo "OK"
}

stop() {
	:
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
